const tablesInital: string = `
--
-- PostgreSQL database dump
--

-- Dumped from database version 14.0
-- Dumped by pg_dump version 14.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: class; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.class (
    id bigint NOT NULL,
    name text,
    "educationLevel" text,
    teacher bigint,
    "schoolYear" text
);


--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roadMap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public."roadMap" (
    id bigint NOT NULL,
    "teachingPlatform" bigint,
    "teachingStage" bigint,
    "teachingStrategy" bigint,
    tools bigint,
    "numberOfStudents" integer,
    "studentAgeMin" integer[],
    teacher bigint
);


--
-- Name: road-map_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."roadMap" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."road-map_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.teacher (
    id bigint NOT NULL,
    name text,
    email text,
    genre text,
    "birthDate" date,
    nationality text,
    estate text,
    city text,
    "teachingTime" text,
    "academicEducation" text
);


--
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachingPlatform; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public."teachingPlatform" (
    id bigint NOT NULL,
    web bit(1),
    desktop bit(1),
    mobile bit(1),
    "noPlataform" bit(1)
);


--
-- Name: teaching platform_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."teachingPlatform" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."teaching platform_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachingStage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public."teachingStage" (
    id bigint NOT NULL,
    kindergarten bit(1),
    "elementarySchool1" bit(1),
    "elementarySchool2" bit(1),
    "highSchool" bit(1),
    "vocationalEducation" bit(1),
    "universityGraduate" bit(1),
    postgraduate bit(1),
    "nonFormalTeaching" bit(1)
);


--
-- Name: teaching-stage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."teachingStage" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."teaching-stage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachingStrategy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public."teachingStrategy" (
    id bigint NOT NULL,
    "gameDevelopment" bit(1),
    robotics bit(1),
    "blockProgramming" bit(1),
    "appDevelopment" bit(1),
    "unpluggedComputing" bit(1),
    "conventionalProgramming" bit(1)
);


--
-- Name: teaching-strategy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."teachingStrategy" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."teaching-strategy_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tools; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tools (
    id bigint NOT NULL,
    scratch bit(1),
    "appInventor" bit(1),
    snap bit(1),
    "mapBlocks" bit(1),
    "ctBlocks" bit(1),
    "pencilCode" bit(1),
    "noTools" bit(1)
);


--
-- Name: tools_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tools ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tools_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: roadMap road-map_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roadMap"
    ADD CONSTRAINT "road-map_pkey" PRIMARY KEY (id);


--
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);


--
-- Name: teachingPlatform teaching platform_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."teachingPlatform"
    ADD CONSTRAINT "teaching platform_pkey" PRIMARY KEY (id);


--
-- Name: teachingStage teaching-stage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."teachingStage"
    ADD CONSTRAINT "teaching-stage_pkey" PRIMARY KEY (id);


--
-- Name: teachingStrategy teaching-strategy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."teachingStrategy"
    ADD CONSTRAINT "teaching-strategy_pkey" PRIMARY KEY (id);


--
-- Name: tools tools_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tools
    ADD CONSTRAINT tools_pkey PRIMARY KEY (id);


--
-- Name: class fk_teacher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT fk_teacher FOREIGN KEY (teacher) REFERENCES public.teacher(id) NOT VALID;


--
-- Name: roadMap teacherFK; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roadMap"
    ADD CONSTRAINT "teacherFK" FOREIGN KEY (teacher) REFERENCES public.teacher(id) NOT VALID;


--
-- Name: roadMap teachingPlataformFk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roadMap"
    ADD CONSTRAINT "teachingPlataformFk" FOREIGN KEY ("teachingPlatform") REFERENCES public."teachingPlatform"(id) NOT VALID;


--
-- Name: roadMap teachingStageFk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roadMap"
    ADD CONSTRAINT "teachingStageFk" FOREIGN KEY ("teachingStage") REFERENCES public."teachingStage"(id) NOT VALID;


--
-- Name: roadMap teachingStrategyFK; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roadMap"
    ADD CONSTRAINT "teachingStrategyFK" FOREIGN KEY ("teachingStrategy") REFERENCES public."teachingStrategy"(id) NOT VALID;


--
-- Name: roadMap toolsFK; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roadMap"
    ADD CONSTRAINT "toolsFK" FOREIGN KEY (tools) REFERENCES public.tools(id) NOT VALID;


--
-- PostgreSQL database dump complete
--


`;

export default tablesInital;